### PR TITLE
Deletion of categories now deletes all the lineItems of its products

### PR DESCRIPTION
**Pull request by alexjamesmalcolm**

### CODE REVIEW

**Review by theoccasionalist — APPROVED** [review]
Cascading orphans.

**Comment by alexjamesmalcolm** [comment]
This isn't royal forklifts, Matt, we delete our branches here at PantryPlus.

**Comment by theoccasionalist** [comment]
I've fallen from the path, I confess.

The app was due today. Should I entreat our   client for a new due date?

**Comment by alexjamesmalcolm** [comment]
Yeah, I think so. Does Kathy know about the first-day problem? It'd be cool
if the food pantry set up a wifi hotspot so people could order food in
line. I was thinking that the pushed back launch date could give the food
pantry time to set that up. I need some cooperation on their part so this
app is actually used.

**Comment by theoccasionalist** [comment]
No worries, the pick up date was pushed back to September 15th.  On the
WiFi issue, the idea (at least on Kathy's end) is that we have people place
orders from either work or home, so that their orders are placed in advance
from some other place than the pantry. WiFi at the pantry shouldn't be an
issue then.

I should be getting internet this weekish, so I can start coding remotely
hopefully.

Also, I should forward some nice words from Kathy.

**Comment by theoccasionalist** [comment]
I'm not sure if that cleared up the concern, but that is, we don't actually have to be there physically for the pick up date (or ordering). This next "demo" is supposed to be more or less how the app is going to be used in normal circumstances.

Also, I'm not quite sure how to forward nice words from Kathy using my phone.

Is this the most comments on a pull request?

**Pull request merged**
